language: csharp
solution: EasyCaching.sln
dist: xenial
sudo: required    
dotnet: 3.0.100
mono: none

services:
  - memcached
  - redis-server

os:
  - linux
  - osx
  
osx_image: xcode9.4

branches:
  only:
    - master
    - dev
 
script:
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  #- if test "$TRAVIS_OS_NAME" == "linux"; then dotnet test -c Release ./test/EasyCaching.UnitTests/EasyCaching.UnitTests.csproj; fi
