language: csharp

solution: EasyCaching.sln

sudo: required

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - CONFIGURATION=Release
    
dotnet: 2.0.0

mono: none

os:
  - linux
  - osx
  
osx_image: xcode9.1

branches:
  only:
    - master
 
script:
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
