language: csharp

solution: EasyCaching.sln

sudo: required
    
dotnet: 2.0.0

mono: none

services:
  - memcached
  - redis-server

os:
  - linux
  - osx
  
osx_image: xcode9.1

branches:
  only:
    - master
 
script:
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - dotnet test -c Release ./test/EasyCaching.UnitTests/EasyCaching.UnitTests.csproj
