version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
clone_folder: C:\projects\easycaching\
install:
- cmd: >-
    cd C:\projects\easycaching\tools\RedisConfigs\3.0.503


    redis-server.exe --service-install --service-name "redis-6379" "..\Basic\master-6379.conf"


    net start redis-6379


    cd C:\projects\easycaching
before_build:
- cmd: dotnet restore
build:
  project: EasyCaching.sln
  parallel: true
  verbosity: minimal
test_script:
- cmd: >-
    dotnet test -c Release --no-build .\test\EasyCaching.Memory.Test\EasyCaching.Memory.Test.csproj


    dotnet test -c Release --no-build .\test\EasyCaching.Redis.Test\EasyCaching.Redis.Test.csproj


    dotnet test -c Release --no-build .\test\EasyCaching.Serialization.Json.Test\EasyCaching.Serialization.Json.Test.csproj